steps:
    - id: "Docker compose"
      name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
      args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

    - id: "wait for it"
      name: 'gcr.io/cloud-builders/docker'
      args: ['exec', '-t', 'app', 'dockerize', '-wait', 'http://localhost:3000', '-timeout', '50s']      
    
    - id: "running tests"
      name: 'gcr.io/cloud-builders/docker'
      args: ['exec', '-t', 'app', 'npm', 'run', 'test']